### ISSUE TITLE
Is `configuration` necessary?

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-yaml-spec#5]
E.g. we have,

```yaml
configuration:
      propertyIRI: https://schema.metadatacenter.org/properties/40db89ca-fe47-4756-ad4d-5519697d2827
      overrideLabel: Textfield
      overrideDescription: Help Text
      multiple: true
      minItems: 0
      maxItems: 7
```

Why do I have to nest these things inside a configuration object?  Why not at the top level for a child?
